name: ngocanh
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.1
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  hexcolor: ^2.0.5
  shared_preferences: ^2.0.8
  google_fonts: ^2.1.0
  fluttertoast: ^8.0.8
  theme_provider: ^0.5.0
  animated_toggle_switch: ^0.2.1 
  slide_switcher: ^1.1.2
  bot_toast: ^4.0.1
  gradients: ^0.1.1+1
  animated_splash_screen: ^1.1.0
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.5
  firebase_crashlytics: ^2.2.4
  http: ^0.13.4
  google_sign_in: ^5.1.1
  flutter_facebook_auth: ^4.1.2
  easy_localization: ^3.0.0
  file_picker: ^5.2.5
  video_player: ^2.5.2
  multi_image_layout: 0.0.6
  video_viewer: ^1.2.7
  progress_state_button: ^1.0.4
  nine_grid_view: ^2.0.0
  video_thumbnail: ^0.5.3
  search_app_bar_page: ^2.1.5
  stacked_card_carousel: ^0.0.4
  flutter_local_notifications: ^9.2.0
  firebase_messaging: ^11.2.6
  cloud_firestore: ^3.1.8
  flutter_lints: ^1.0.0
  skeletons: ^0.0.3
  material_tag_editor: ^0.1.2
  readmore: ^2.2.0
  expandable: ^5.0.1
  flutter_email_sender: ^5.2.0
  url_launcher: ^6.1.10
  emailjs: ^1.1.0
  flutter_countdown_timer: ^4.1.0
  timer_count_down: ^2.2.2
  file: ^6.1.4
  # flutter_facebook_login: ^3.0.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  cloud_firestore_platform_interface: 5.7.7
  firebase_auth_platform_interface: 6.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/social.png
    - assets/images/social.jpg
    - assets/images/Google_Logo.png
    - assets/images/facebook_logo.png
    - assets/images/loading_icon.gif
    - assets/images/


  fonts:
    - family: Jannah
      fonts:
        - asset: fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: fonts/icons.ttf

