// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPr2-eLsBdCiDqZv5Ka829YO8Q5CK5zYU',
    appId: '1:795844662762:web:42cf162df0217c43508e93',
    messagingSenderId: '795844662762',
    projectId: 'test3-12053',
    authDomain: 'test3-12053.firebaseapp.com',
    storageBucket: 'test3-12053.appspot.com',
    measurementId: 'G-PPQC9D7VVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb_ebVSEtBXnfGyrtXgK6GYpKD9EtX2Gk',
    appId: '1:795844662762:android:3135a158e2f0dee2508e93',
    messagingSenderId: '795844662762',
    projectId: 'test3-12053',
    storageBucket: 'test3-12053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGGgSpYTnlwzFGZmSbc68IywVIcRg-HNI',
    appId: '1:795844662762:ios:5e5ebc9e2abd496b508e93',
    messagingSenderId: '795844662762',
    projectId: 'test3-12053',
    storageBucket: 'test3-12053.appspot.com',
    androidClientId: '795844662762-11hkif7f5a9e6msncsa0vgqu7vcfq3q6.apps.googleusercontent.com',
    iosClientId: '795844662762-vqqgcg7i1641sqopg1qtn59q8suo7u1i.apps.googleusercontent.com',
    iosBundleId: 'com.ngocanh.ngocanh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGGgSpYTnlwzFGZmSbc68IywVIcRg-HNI',
    appId: '1:795844662762:ios:5e5ebc9e2abd496b508e93',
    messagingSenderId: '795844662762',
    projectId: 'test3-12053',
    storageBucket: 'test3-12053.appspot.com',
    androidClientId: '795844662762-11hkif7f5a9e6msncsa0vgqu7vcfq3q6.apps.googleusercontent.com',
    iosClientId: '795844662762-vqqgcg7i1641sqopg1qtn59q8suo7u1i.apps.googleusercontent.com',
    iosBundleId: 'com.ngocanh.ngocanh',
  );
}
